apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-j
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mysql-j
        role: mysql-j
    spec:
      containers:
        - name: mysql-j
          image: mysql:8.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: mysql-j

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-j
  labels:
    app: mysql-j
spec:
  selector:
   app: mysql-j
  type: LoadBalancer
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: mysql-j
